version: '3.8'
services:
  orfarchiv-db:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - orfarchiv-db-network
    volumes:
      - orfarchiv:/data/db
    restart: unless-stopped
  orfarchiv-db-ui:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=orfarchiv-db
    ports:
      - '3002:8081'
    networks:
      - orfarchiv-db-network
    restart: unless-stopped
networks:
  orfarchiv-db-network:
volumes:
  orfarchiv:
