version: '3.8'
services:
  orfarchiv-db:
    image: mongodb/mongodb-atlas-local
    ports:
      - '27017:27017'
    networks:
      - orfarchiv-db-network
    volumes:
      - orfarchiv:/data/db
      - orfarchiv-mongot:/data/mongot
    restart: unless-stopped
  orfarchiv-db-ui:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://orfarchiv-db:27017/?directConnection=true
    ports:
      - '3002:8081'
    networks:
      - orfarchiv-db-network
    depends_on:
      orfarchiv-db:
        condition: service_healthy
    restart: unless-stopped
networks:
  orfarchiv-db-network:
volumes:
  orfarchiv:
  orfarchiv-mongot:
